# Generated by Django 4.1.5 on 2023-02-09 10:28

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usermodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=home.models.nameFile),
        ),
    ]
