# Generated by Django 4.1.6 on 2023-02-26 07:41

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_usermodel_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=home.models.productImageFile)),
                ('product_dic', models.CharField(blank=True, max_length=64, null=True)),
                ('product_price', models.FloatField(max_length=5)),
                ('product_discount_price', models.FloatField(blank=True, max_length=5, null=True)),
                ('product_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
