# Generated by Django 4.1.7 on 2023-02-26 16:19

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_productmodel_alter_usermodel_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product_image',
        ),
        migrations.CreateModel(
            name='ProductImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=home.models.productImageFile)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='home.productmodel')),
            ],
        ),
    ]
