# Generated by Django 4.1.7 on 2023-02-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_productmodel_product_image_productimagesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimagesmodel',
            old_name='image_id',
            new_name='product_id',
        ),
    ]
